<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $noticeTitle }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #111; margin: 28px; line-height: 1.5; }
        h1 { font-size: 18px; margin: 0 0 6px; }
        h2 { font-size: 14px; margin: 20px 0 8px; }
        .muted { color: #555; font-size: 10px; }
        .header { width: 100%; margin-bottom: 24px; }
        .header td { vertical-align: top; width: 50%; }
        .right { text-align: right; }
        .box { border: 1px solid #ccc; padding: 12px 14px; margin: 16px 0; background: #fafafa; }
        .amount { font-size: 16px; font-weight: bold; }
        .footer { margin-top: 36px; font-size: 10px; color: #444; border-top: 1px solid #ddd; padding-top: 12px; }
    </style>
</head>
<body>
    <table class="header">
        <tr>
            <td>
                <h1>{{ $company?->name ?? 'Property Management' }}</h1>
                <p class="muted">
                    @if($company?->address){{ $company->address }}<br>@endif
                    @if($company?->city){{ $company->city }}@endif
                    @if($company?->country), {{ $company->country }}@endif
                    @if($company?->phone)<br>{{ $company->phone }}@endif
                    @if($company?->email)<br>{{ $company->email }}@endif
                </p>
            </td>
            <td class="right">
                <strong style="font-size: 15px;">{{ strtoupper($noticeTitle) }}</strong><br>
                <span class="muted">Date: {{ $generatedAt }}</span><br>
                <span class="muted">Invoice: {{ $invoice->invoice_number }}</span>
            </td>
        </tr>
    </table>

    <p><strong>To:</strong> {{ $tenantName }}</p>
    <p>
        <strong>Property:</strong>
        {{ $invoice->apartment?->building?->name ?? 'Building' }}
        — Unit {{ $invoice->apartment?->unit_number ?? '—' }}
    </p>

    <div class="box">
        <p><strong>Outstanding balance:</strong> <span class="amount">{{ number_format((float) $invoice->balance_due, 2) }}</span></p>
        <p><strong>Original due date:</strong> {{ $invoice->due_date?->format('Y-m-d') ?? '—' }}</p>
        @if($daysOverdue > 0)
            <p><strong>Days overdue:</strong> {{ $daysOverdue }}</p>
        @endif
    </div>

    <h2>{{ $noticeHeading }}</h2>
    <p>{!! nl2br(e($noticeBody)) !!}</p>

    <p>Please contact our office immediately to arrange payment or discuss payment arrangements.</p>

    <div class="footer">
        This notice was generated by {{ $company?->name ?? 'the property management office' }}.
        Reference: {{ $invoice->invoice_number }} / {{ $noticeType->value }}.
    </div>
</body>
</html>
